# Generated by Django 4.2.5 on 2023-09-16 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="fees_in_world",
            new_name="fees",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="fees_in_usa",
        ),
    ]
