# Generated by Django 4.2.5 on 2023-09-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_saga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saga',
            name='movies',
        ),
        migrations.AddField(
            model_name='saga',
            name='movies',
            field=models.ManyToManyField(related_name='saga', to='mainapp.movie'),
        ),
    ]
