# Generated by Django 4.2.6 on 2023-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_troubleshoot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, upload_to='movie_videos'),
        ),
        migrations.AlterField(
            model_name='troubleshoot',
            name='category',
            field=models.CharField(choices=[('no_error_category', 'Not selected'), ('page_load_error', 'The page does not load'), ('quality_error', 'Movie quality is bad'), ('account_error', "Can't change account information")], default='no_error_category', max_length=150),
        ),
    ]
