# Generated by Django 4.2.6 on 2023-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_movie_video_alter_troubleshoot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
