# Generated by Django 5.0.4 on 2024-05-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_rating_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
